---

- name: apply common configuration to all nodes
  hosts: all
  user: root
  vars_files:
    - "secrets/ansible_secrets.yml"
  roles:
    - common

- name: deploy MySQL and PostgreSQL
  hosts: dbserver
  user: root
  roles:
    - db

- name: configure and deploy webservers and application code
  hosts: webserver
  user: root
  roles:
    - web

- name: setup backups
  hosts: backupserver
  user: root
  vars_files:
    - "secrets/ansible_secrets.yml"
  roles:
    - backup
