---

- name: install packages
  apt: pkg={{ item }} state=installed update_cache=true
  sudo: true
  with_items:
    - davfs2

- name: create backup sirectory
  file:
    path: "{{ yabackup_mountdir }}"
    owner: "{{ yabackup_owner_user }}"
    group: "{{ yabackup_owner_group }}"
    mode: 0755
    recurse: yes
    state: directory

- name: register yandex disk credentials
  lineinfile: >
    dest=/etc/davfs2/secrets
    state=present
    regexp="{{ yabackup_webdav_url }}"
    insertafter=EOF
    line="{{ yabackup_webdav_url }} {{yabackup_webdav_user }} {{ yabackup_webdav_password }}"

- name: mount yabackup_disk
  mount: >
    name="{{ yabackup_mountdir }}"
    src="{{ yabackup_webdav_url }}"
    fstype="davfs"
    opts="rw,_netdev,users,exec"
    state=mounted
