---

 - name: Prepare app directory
   file: >
     path="{{ sites.path }}/{{ item.0.name }}/{{ item.1 }}" state=directory
     recurse=true
     owner="www-data"
     group="www-data"
   with_nested:
     - sites.php
     - ["current/public", "shared/log", "shared/config", "shared/tmp"]

 - name: Create nginx configs
   template: >
     src="app.nginx.conf.j2"
     dest="{{ nginx_dir }}/sites-available/{{ item.name }}"
   with_items: sites.php
   notify: reload nginx

 - name: Create php-fpm configs
   template: >
     src="app.php-fpm.conf.j2"
     dest="{{ phpfpm_confdir }}/{{ item.name }}.conf"
   with_items: sites.php
   notify: php5-fpm reload

 - name: Enable nginx config
   file: >
     src="{{ nginx_dir }}/sites-available/{{ item.name }}"
     dest="{{ nginx_dir }}/sites-enabled/{{ item.name }}"
     state=link
   with_items: sites.php
   notify: reload nginx

 - name: Create mysql database
   mysql_db: name={{ item.name }} state=present
   with_items: sites.php

 - name: Create mysql user
   mysql_user: >
     name="{{ item.name }}"
     password="{{ item.name }}"
     priv={{ item.name }}.*:ALL
     state=present
   with_items: sites.php

 - name: setup brothers site
   template: >
     src="ipsite.config.php.j2"
     dest="{{ sites.path }}/{{ item.name }}/shared/config/config.php"
     owner="www-data"
     group="www-data"
   when: item.has_key("ipsite")
   with_items: sites.php
