 - name: Nginx | Add the nginx repository
   apt_repository:
     repo: ppa:nginx/stable

 - name: Nginx | Make sure the nginx directory exists
   file:
     path: "{{nginx_dir}}"
     owner: root
     group: root
     mode: 0755
     recurse: yes
     state: directory

 - name: Nginx | Make sure the nginx log directory exists
   file:
     path: "{{nginx_log_dir}}"
     owner: root
     group: root
     mode: 0755
     recurse: yes
     state: directory

 - name: Nginx | Make sure the sites-available, sites-enabled and conf.d directories exist
   file:
     path: "{{nginx_dir}}/{{item}}"
     owner: root
     group: root
     mode: 0755
     recurse: yes
     state: directory
   with_items: ["sites-available", "sites-enabled", "conf.d"]

 - name: Nginx | Make sure nginx is installed (package)
   apt:
     pkg: nginx
     state: present
   notify:
     - restart nginx

 - name: remove default host
   file: >
     dest="{{nginx_dir}}/sites-available/default"
     src="{{nginx_dir}}/sites-enabled/default"
     state=absent
   notify:
     - test nginx

 - name: setup custom log
   template: >
     src=nginx.custom_log.conf.j2
     dest="{{nginx_dir}}/conf.d/custom_log.conf"
   notify:
     - restart nginx

 - name: setup default host
   template: >
     src=nginx.default.conf.j2
     dest="{{nginx_dir}}/sites-available/default.conf"
   notify:
     - test nginx

 - name: enable default host
   file: >
     src="{{nginx_dir}}/sites-available/default.conf"
     dest="{{nginx_dir}}/sites-enabled/default.conf"
     state=link
   notify:
     - restart nginx

 - name: start nginx
   service: name=nginx state=started
