 - name: create swap space
   command: dd if=/dev/zero of=/swapfile bs=1024 count=512k
   when: ansible_swaptotal_mb < 1

 - name: make swap
   command: mkswap /swapfile
   when: ansible_swaptotal_mb < 1

 - name: set swapfile chown+chmod
   sudo: yes
   file: >
     path=/swapfile
     owner=root
     group=root
     mode=0600

 - name: add swap to fstab
   lineinfile: >
     dest=/etc/fstab
     regexp="swapfile"
     line="/swapfile none swap sw 0 0"
     state=present
   notify: swapon

 - name: set swapiness
   sysctl: >
     name="vm.swappiness"
     value="10"
     sysctl_set=yes
     state=present
     reload=yes
   notify:
     - swapoff
     - swapon
